### ISSUE TITLE
GHC 8.6 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#324]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 8.6:

* [x] In 6eb213390729706e1840eaa67124caf26ac839f3 and ddd353afa3c92a53c00f22919611f734eaa0f29f, I added some CPP to temporarily support both GHC 8.4 and HEAD. We should remove this CPP once we drop support for GHC 8.4.

In addition, there are some other things that we could do if some new language extensions make it in to GHC 8.6:

* Template Haskell changes. In particular:
  * [x] Update `th-desugar` to support the new `ViaStrategy` AST form, as well as `QuantifiedConstraints`. (goldfirere/th-desugar#86)
  * [x] Just as `singletons` does not support `GeneralizedNewtypeDeriving`, it will also not support `DerivingVia`. Implement this.

* [x] If `QuantifiedConstraints` lands in 8.6, then we can completely do away with the `ShowSing` class. We can take code like this:

   ```haskell
   instance (ShowSing a, ShowSing b) => ShowSing (Either a b) where showsSingPrec = ...
   instance (ShowSing a, ShowSing b) => Show (Sing (e :: Either a b)) where showsPrec = showsSingPrec
   ```

   And replace it with a much more concise equivalent:

   ```haskell
   type ShowSing k = (forall (z :: k). Show (Sing z) :: Constraint)
   deriving instance (ShowSing a, ShowSing b) => Show (Sing (e :: Either a b))
   ```

   See the `quantified-constraints` branch for a WIP implementation of this.
* [x] Now that [GHC is smarter about kind inference in CUSKs](http://git.haskell.org/ghc.git/commit/12794287174146f982257cdeffd491e3e23838dc), we may be able to remove some superfluous kind signatures on `k -> Type`-kinded things (e.g., in `Functor` or `Const`).
* [x] Mention in the `README` that you'll likely need to enable `NoStarIsType` in order to profitably use `PNum(type (*))`.

**Comment by RyanGlScott** [comment]
#351 and #352 implement these.

**Comment by RyanGlScott** [comment]
At this point, GHC 8.6 is due to be released Real Soon Now, and I don't expect any further changes that would affect the expected test results (74176fa8e8392f21e116dd2b4b259aed2076d7c9 should be the last of them, I think). Are we ready to release `th-desugar-1.9` and `singletons-2.5` to Hackage?

**Comment by goldfirere** [comment]
Go for it. :)

**Comment by RyanGlScott** [comment]
[`th-desugar-1.9`](http://hackage.haskell.org/package/th-desugar-1.9) and [`singletons-2.5`](http://hackage.haskell.org/package/singletons-2.5) have been released to Hackage.
