### ISSUE TITLE
GHC 8.8 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#356]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 8.8:

* [x] Bump the `th-desugar` submodule to incorporate changes from goldfirere/th-desugar#105.
* [x] `singletons` is completely borked at the moment on GHC HEAD due to #357. Figure out how to work around this.
* [X] Adapt to the `MonadFail` proposal.
  * [ ] When we require GHC 8.8 or later to build, we should remove qualified imports to `Control.Monad.Fail`, as they will no longer be necessary due to `MonadFail` being exported by the `Prelude`.
* [X] Now that [`!`](https://gitlab.haskell.org/ghc/ghc/commit/bd7898537768f936d05c0c83eef1cd9b00933347) and [`.`](https://gitlab.haskell.org/ghc/ghc/commit/887454d8889ca5dbba70425de41d97939cb9ac60) can be parsed as type operators, we should remove the special-casing for `(!)` and `(.)`. (See [`Note [Special cases for (.) and (!)]`](https://github.com/goldfirere/singletons/blob/a9db6ff634d00a11a74595187e4ed935715f6626/src/Data/Singletons/Names.hs#L355-L361).)
* [ ] We can now rewrite `ApplyTyCon`:

   https://github.com/goldfirere/singletons/blob/ea63077a16b27f56ad5ef53461abdb57bfefc633/src/Data/Singletons/Internal.hs#L204-L206

   To use visible kind application:

   ```haskell
   type family ApplyTyCon :: (k1 -> k2) -> (k1 ~> unmatchable_fun) where
     ApplyTyCon @k1 @(k2 -> k3) @unmatchable_fun = ApplyTyConAux2
     ApplyTyCon @k1 @k2         @k2              = ApplyTyConAux1
   ```

   This change isn't strictly necessary, but it does make the right-hand sides a little less noisy.

**Comment by RyanGlScott** [comment]
The third bullet point (about the `(!)` and `(.)` type operators) won't be possible unless we can devise a fix for [Trac #16339](https://ghc.haskell.org/trac/ghc/ticket/16339), which prevents us from replacing `type (:.)` with `type (.)` in `singletons`' export lists.

**Comment by int-index** [comment]
The fix for #16339 has been merged to the `ghc-8.8` branch.

**Comment by RyanGlScott** [comment]
With the merging of #393 and #400, I think every change that I wanted to get in before the next release has landed. Once GHC 8.8.1-rc1 is out, I think we can consider making an official Hackage release (unless anyone else thinks of some other change that deserves to make it in?).
