### ISSUE TITLE
GHC 8.10 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#385]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 8.10:

* [x] Update `th-desugar` (see goldfirere/th-desugar#114).
* [x] Give #378 some serious consideration
  * After some serious consideration, I have come to the conclusion that a full fix for #378 just isn't possible at the moment—see my explanation at https://github.com/goldfirere/singletons/issues/378#issuecomment-584096320. I have, however, documented the fact that `singletons` doesn't fully support `TypeApplications` in the `README`.
* [x] Some simplifications can be made using visible dependent quantification (VDQ):
  * This comment in `Data.Singletons.Promote.Defun` suggests some code cleanup that would be possible with VDQ:

    https://github.com/goldfirere/singletons/blob/ea63077a16b27f56ad5ef53461abdb57bfefc633/src/Data/Singletons/Promote/Defun.hs#L405-L412
  * Current, `Sigma` is defined to be:

    https://github.com/goldfirere/singletons/blob/ea63077a16b27f56ad5ef53461abdb57bfefc633/src/Data/Singletons/Sigma.hs#L34

    Why not:

    ```haskell
    type Sigma :: forall s -> (s ~> Type) -> Type
    data Sigma s t where
    ```
  * Currently, we need `ImpredicativeTypes` in `Data.Singletons.Sigma` due to this type synonym:

    https://github.com/goldfirere/singletons/blob/ea63077a16b27f56ad5ef53461abdb57bfefc633/src/Data/Singletons/Sigma.hs#L39

    However, we could eliminate the use of `ImpredicativeTypes` altogether by just giving `Σ` a standalone kind signature:

    ```haskell
    type Σ :: forall s -> (s ~> Type) -> Type
    type Σ = Sigma
    ```
* [x] Future-proof `singletons` against the deprecation of the `CUSKs` extension by giving more declarations standalone kind signatures:
  * `ApplyTyCon`:

    ```hs
    type ApplyTyCon :: (k1 -> k2) -> (k1 ~> unmatchable_fun)
    type family ApplyTyCon where ...
    ```
  * `SndSigma`:

    ```hs
    type SndSigma :: forall s t. forall (sig :: Sigma s t) -> t @@ FstSigma sig
    type family SndSigma sig where ...
    ```

**Comment by RyanGlScott** [comment]
Now that GHC 8.10.1 is out, I plan to release `th-desugar-1.11` and `singletons-2.7` some time in the next few days (unless there are any last-minute objections).

**Comment by goldfirere** [comment]
No objections from me, certainly!

**Comment by RyanGlScott** [comment]
Fixed with the Hackage release of [`singletons-2.7`](http://hackage.haskell.org/package/singletons-2.7).
