### ISSUE TITLE
GHC 9.0 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#439]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.0:

* [x] Update `th-desugar` (see goldfirere/th-desugar#141)
* [x] Consider changing the definition of `ShowSing` to make it easier to derive (#426)
* [x] Make `OptionsM` an instance of the new `Quote` class from `Language.Haskell.TH.Syntax`. That way, we can omit the use of `lift` in code like this from the `README`:

   ```hs
   import Control.Monad.Trans.Class
   import Data.Singletons.TH
   import Data.Singletons.TH.Options
   import Language.Haskell.TH (Name, mkName, nameBase)
   
   $(let myPrefix :: Name -> Name
         myPrefix name = mkName ("MyS" ++ nameBase name) in
   
         withOptions defaultOptions{singledDataConName = myPrefix} $
         singletons $ lift [d| data T = MkT |])
   ```
* [X] Simplify some code using [explicit specificity](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0099-explicit-specificity.rst):

  * The type of `demote`:

    https://github.com/goldfirere/singletons/blob/efb2e395353636f07b95c908792b5eeac6e79d37/src/Data/Singletons/Internal.hs#L602-L603

    Can be made cleaner:

    ```hs
    demote :: forall {k} (a :: k). (SingKind k, SingI a) => Demote k
    ```
  * `SingI`:

    https://github.com/goldfirere/singletons/blob/efb2e395353636f07b95c908792b5eeac6e79d37/src/Data/Singletons/Internal.hs#L115-L118

    Can be given a standalone kind signature:

    ```hs
    type  SingI :: forall {k}. k -> Constraint
    class SingI a where ...
    ```
* [x] `Note [Preserve the order of type variables during singling]` describes several ugly hacks that are required due to Template Haskell's inability to distinguish specified from inferred type variables. Here is one such hack, described in `Wrinkle 2: The TH reification swamp`:

    https://github.com/goldfirere/singletons/blob/f6c4223d3674ea323346ecb03b19c389bac2cdc8/src/Data/Singletons/Single/Type.hs#L216-L220

    Here is another, described in `Wrinkle 3: Where to put explicit kind annotations`:

    https://github.com/goldfirere/singletons/blob/f6c4223d3674ea323346ecb03b19c389bac2cdc8/src/Data/Singletons/Single/Type.hs#L273-L292

    These hacks should be revisited.

**Comment by RyanGlScott** [comment]
I had hoped that having explicit specificities in `TyVarBndr`s would render `Wrinkle 2: The TH reification swamp` and `Wrinkle 3: Where to put explicit kind annotations` above obsolete, but sadly, that is not the case. They're less likely to pop up, but they can still surface in certain situations. Consider this example, for instance:

```hs
{-# LANGUAGE PolyKinds, ... #-}
data P a = MkP
$(genSingletons [''P])
```

Ideally, we would single the `MkP` data constructor like so:

```hs
data SP z where
  SMkP :: forall {k} (a :: k). SP (MkP @a)
```

However, it's shockingly difficult to accomplish this, even with GHC 9.0. To understand why, consider what happens when we invoke `$(genSingletons [''P])` above. First, we reify `P` to get this:

```hs
DataD
  [] ''P [KindedTV a () (VarT k)] Nothing
  [NormalC 'MkP []]
  []
```

Next, we use `th-desugar` to desugar this `DataD` into a `DDataD`. There is one non-trivial aspect to this: when desugaring data declarations, we always convert them to use GADT syntax, even if they were originally declared using Haskell98-style syntax, like what `P` uses. This is reflected in the type of `DCon`:

```hs
data DCon = DCon [DTyVarBndrSpec] DCxt Name DConFields DType
```

Herein lies the rub. Note that `DCon` uses `[DTyVarBndrSpec]`, while `DDataD` above uses `[DTyVarBndrUnit]`. As a result, when converting the `MkP` constructor to a `DCon`, we have no information about the specificity of the `k` kind variable, so we are forced to guess what it may be. We guess that it is specified, thus desugaring `P` to this:

```hs
data P (a :: k) where
  MkP :: forall k (a :: k). P a
```

Not good! `singletons` will use this in the implementation of `genSingletons`, which would mislead it into singling `P` like so:

```hs
data SP z where
  SMkP :: forall k (a :: k). SP (MkP @k @a) -- Doesn't kind-check!
```

Ugh.

-----

What can be done about this? I could envision a more complicated desugaring algorithm where we attempt to reverse engineer the specificities of kind variables like `k`, but this sounds fragile, especially given [`th-desugar`'s already limited support for kind inference](https://github.com/goldfirere/th-desugar/tree/ca761285741c16c704a4044f551faf4292432d6a#limited-support-for-kind-inference) _vis-à-vis_ desugaring Haskell98-style data declarations. As a result, I'm inclined to park this issue until GHC gains the ability to properly mark the specificities of type variables in `DataD`s (perhaps on the heels of [this MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2464)).

Unfortunately, this means that we won't be able to get rid of `Wrinkle 2: The TH reification swamp` and `Wrinkle 3: Where to put explicit kind annotations` quite yet. I'll make a note to revise the prose in these notes to more accurately reflect the current state of GHC.

**Comment by goldfirere** [comment]
groan. I would argue that GHC should provide more information in its reification. The problem is that we don't yet have `data D @{k} (a :: k) = ...` syntax for it to reify into. (I suppose TH could support that only for reification.)

Someday.

**Comment by RyanGlScott** [comment]
I've opened #484, #485, and #486 to address the three remaining 9.0-related bullet points. These are ready for review.

The only other blocker is [getting a 9.0-compatible release of `th-expand-syns`](https://github.com/DanielSchuessler/th-expand-syns/pull/19), on which `singletons-th` transitively depends.

**Comment by RyanGlScott** [comment]
I've uploaded the following to Hackage:

* [`singletons-3.0`](http://hackage.haskell.org/package/singletons-3.0)
* [`singletons-th-3.0`](http://hackage.haskell.org/package/singletons-th-3.0)
* [`singletons-base-3.0`](http://hackage.haskell.org/package/singletons-base-3.0)
