### ISSUE TITLE
GHC 9.2 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#477]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.2:

* [x] Now that [`Nat` is a synonym for `Natural`](https://gitlab.haskell.org/ghc/ghc/-/commit/8f4f5794eb3504bf2ca093dc5895742395fdbde9#d87dfc77856eeaef6134e28336290ddcbcf18d7d), we no longer need to define the following bogus instances for `Nat`:

   https://github.com/goldfirere/singletons/blob/0261bafe8fe96944d1ee5bd44a6beaf12dc87e3e/singletons-base/src/GHC/TypeLits/Singletons.hs#L63-L88

   Actually, it's less "we no longer need to define" and more "we cannot define". This is because `Natural` already has instances of `Num`, `Eq`, `Ord`, `Enum`, and `Show`, so defining instances for `Nat` (now a type synonym for `Natural`) will result in type errors. See [this `head.hackage` MR](https://gitlab.haskell.org/ghc/head.hackage/-/merge_requests/126) for a rough sketch of a fix we can apply in `singletons`.

   If we do this, we should make sure to update [this section of the `README`](https://github.com/goldfirere/singletons/blob/0261bafe8fe96944d1ee5bd44a6beaf12dc87e3e/README.md#arrows-nat-symbol-and-literals), which claims that `Nat`s need special care. This will no longer be true in GHC 9.2, so we should revise this documentation accordingly.
* [x] Now that characters can be promoted to the type level, a lot of the hacks currently used in `Text.Show.Singletons` ought to be revisited. See #487.
* [x] Consider supporting [type applications in patterns](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2464). See #489.
* [x] With the advent of `GHC2021`, many of the language extensions in [this list](https://github.com/goldfirere/singletons/blob/662dd72db5fedcc4f91326709c959f593df01a56/singletons-base/tests/SingletonsBaseTestSuiteUtils.hs#L49-L73) can be dropped. On the other hand, we will need to explicitly disable some language extensions implied by `GHC2021`. One such extension is `NamedWildCards`. This poses issues when singling code like this:

  ```hs
  f _x = ()
  ```

  This is because `singletons` will single it to the following code:

  ```hs
  sF (_sx :: Sing _x) = STuple0
  ```

  If `NamedWildCards` is enabled, then GHC will treat the `_x` in `Sing _x` as a wildcard instead of a variable name. We'd prefer it be a variable name, so we should disable `NamedWildCards` in the test suite and encourage users to do the same in the `README`.
* [x] Manually upload the Haddocks after uploading `singletons-th`/`singletons-base` to Hackage.

**Comment by RyanGlScott** [comment]
I've uploaded the following to Hackage:

* [`singletons-3.0.1`](https://hackage.haskell.org/package/singletons-3.0.1)
* [`singletons-th-3.1`](https://hackage.haskell.org/package/singletons-th-3.1)
* [`singletons-base-3.1`](https://hackage.haskell.org/package/singletons-base-3.1)
