### ISSUE TITLE
GHC 9.4 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#497]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.4:

* [x] Update `th-desugar`. See goldfirere/th-desugar#157.
* [x] Now that [GHC#16646](https://gitlab.haskell.org/ghc/ghc/-/issues/16646) and [GHC#19667](https://gitlab.haskell.org/ghc/ghc/-/issues/19667) are fixed, we can define `withSingI` in terms of [`withDict`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5573) rather than `unsafeCoerce`. See #490.
* [ ] Manually upload the Haddocks after uploading `singletons-th`/`singletons-base` to Hackage.

**Comment by RyanGlScott** [comment]
I have uploaded the following to Hackage, which are compatible with GHC 9.4:

* [`singletons-3.0.2`](https://hackage.haskell.org/package/singletons-3.0.2)
* [`singletons-th-3.1.1`](https://hackage.haskell.org/package/singletons-th-3.1.1)
* [`singletons-base-3.1.1`](https://hackage.haskell.org/package/singletons-base-3.1.1)
