### ISSUE TITLE
GHC 9.6 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#540]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.6:

* [x] Update `th-desugar`. See goldfirere/th-desugar#170.
* [x] Manually upload the Haddocks after uploading `singletons-th`/`singletons-base` to Hackage.
* [x] Adapt to [exporting `SSymbol`, `symbolSing`, etc. (GHC!9064)](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9064).
* [x] #559

**Comment by RyanGlScott** [comment]
I've uploaded these to Hackage:

* [`singletons-th-3.2`](https://hackage.haskell.org/package/singletons-th-3.2)
* [`singletons-base-3.2`](https://hackage.haskell.org/package/singletons-base-3.2)
