### ISSUE TITLE
GHC 9.10 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#569]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.10:

* [x] Update `th-desugar`. See https://github.com/goldfirere/th-desugar/issues/191.
* [x] Manually upload the Haddocks after uploading `singletons-th`/`singletons-base` to Hackage.
* [x] https://github.com/goldfirere/singletons/pull/584
* [x] #566

**Comment by RyanGlScott** [comment]
* [`singletons-3.0.3`](https://hackage.haskell.org/package/singletons-3.0.3)
* [`singletons-th-3.4`](https://hackage.haskell.org/package/singletons-th-3.4)
* [`singletons-base-3.4`](https://hackage.haskell.org/package/singletons-base-3.4)
