### ISSUE TITLE
GHC 9.12 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#619]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.12:

* [x] Update `th-desugar`. See https://github.com/goldfirere/th-desugar/issues/221.
* [x] Manually upload the Haddocks after uploading `singletons-th`/`singletons-base` to Hackage.
* [x] Require building with GHC 9.12 (#620)

**Comment by RyanGlScott** [comment]
I've uploaded `singletons-{th,base}-3.5` to Hackage.
